# Question 1: Dataset Loading and Initial Exploration

In [1]:
import pandas as pd

In [2]:
# mount google drive in colab
#from google.colab import drive
#drive.mount('/content/drive')

In [3]:
#path='/content/drive/MyDrive/dataset/Heart disease/heart.csv'
#df=pd.read_csv(path)

In [4]:
df=pd.read_csv("heart.csv")

In [5]:
# Display the first five rows of the dataset
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [6]:
# Display the last five rows of the dataset
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [7]:
# Print the shape of the dataset
print(df.shape)

(1025, 14)

# Question 2: Dataset Structure and Missing Value Analysis Using Pandas functions

In [8]:
# Display all column names
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [9]:
# Show dataset information including data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [10]:
# Identify missing values in each column
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

# Question 3: Categorical Data Analysis

In [11]:
# Count the number of patients with heart disease (target = 1) and without heart disease (target = 0)
df['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [12]:
# Count the number of male (sex = 1) and female (sex = 0) patients
df['sex'].value_counts()

sex
1    713
0    312
Name: count, dtype: int64

# Question 4: Data Selection Using iloc

In [13]:
# Select the first 10 rows of the dataset
df.iloc[0:10]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0

In [14]:
# Extract the columns representing age, sex, and cholesterol
df.iloc[:,[0,1,4]]

      age  sex  chol
0      52    1   212
1      53    1   203
2      70    1   174
3      61    1   203
4      62    0   294
...   ...  ...   ...
1020   59    1   221
1021   60    1   258
1022   47    1   275
1023   50    0   254
1024   54    1   188

[1025 rows x 3 columns]

In [15]:
# Select rows from index 20 to 30 and columns from index 0 to 4
df.iloc[20:31,0:5]

    age  sex  cp  trestbps  chol
20   60    1   2       140   185
21   67    0   0       106   223
22   45    1   0       104   208
23   63    0   2       135   252
24   42    0   2       120   209
25   61    0   0       145   307
26   44    1   2       130   233
27   58    0   1       136   319
28   56    1   2       130   256
29   55    0   0       180   327
30   44    1   0       120   169

# Question 5: Data Filtering Using Conditions

In [16]:
# Extract all patients older than 50 years
df[df['age'] > 50 ]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,65,1,3,138,282,1,0,174,0,1.4,1,1,2,0
1017,53,1,0,123,282,0,1,95,1,2.0,1,2,3,0
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [17]:
# Extract patients who have heart disease and a cholesterol level greater than 240
df[(df['target'] == 1) & (df['chol'] > 240)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
16,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
18,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
23,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
1004,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
1008,42,1,1,120,295,0,1,162,0,0.0,2,0,2,1
1011,45,1,1,128,308,0,0,170,0,0.0,2,0,2,1
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1

In [18]:
# Count how many patients satisfy both conditions
((df['target'] == 1) & (df['chol'] > 240)).sum()

np.int64(222)